[package]
name = "kalcite-lsp"
version = "0.14.0"
edition = "2024"
license = "MIT"
rust-version = "1.88"
description = "Language Server Protocol implementation for the Kalcite language"
repository = "https://github.com/Kalcite-Engine/kalcite-lsp"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "io-std", "macros"] }
kalcite-compiler = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "c2e18c26951ee2dd6add883b4934f026e573f8bb" }
kalcite-syntax = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "c2e18c26951ee2dd6add883b4934f026e573f8bb" }
kalcite-project = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "c2e18c26951ee2dd6add883b4934f026e573f8bb" }
kalcite-scene = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "c2e18c26951ee2dd6add883b4934f026e573f8bb" }
kalcite-assets = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "c2e18c26951ee2dd6add883b4934f026e573f8bb" }
kalcite-input = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "c2e18c26951ee2dd6add883b4934f026e573f8bb" }
kalcite-save = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "c2e18c26951ee2dd6add883b4934f026e573f8bb" }
